site_name: pixi-live2d5

docs_dir: docs

site_dir: ../site

repo_url: https://github.com/omniwaifu/pixi-live2d5

nav:
  - Introduction: 'index.md'
  - References:
    - Models: 'models.md'
    - Interactions: 'interactions.md'
    - Motions and Expressions: 'motions_expressions.md'
    - Additional Features: 'additional.md'
    - Configs: 'configs.md'
    - Graphs: 'graphs.md'
  - API Documentation: 'api_index.md'

plugins:
  - search
  - mermaid2:
      version: 10.4.0
      arguments:
        theme: dark

theme:
  name: material
  features:
    - navigation.expand

markdown_extensions:
  - admonition
  - toc:
      permalink: True
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.critic
  - sane_lists
  - def_list
  - attr_list
  - pymdownx.superfences:
      # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
